name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Santosh9519424222
          outputs: dist/snake.svg

      - name: Update snake SVG
        uses: peter-evans/create-or-update-file@v4
        with:
          path: output/github-contribution-grid-snake.svg
          content-file: dist/snake.svg
          commit-message: "update snake"
          token: ${{ secrets.GITHUB_TOKEN }}
